import pyautogui as pya
import cv2, time

print("\nBegin 5 sec Countdown!\n")
count = 5
for i in range(count):
    print(str(count - i) + "." * (count - i))
    time.sleep(1)        
print("\nExecute\n")

pya.click(pya.locateCenterOnScreen('captures\\1-StartButton.png', grayscale=True, confidence=.8))
time.sleep(.5)
pya.click(pya.locateCenterOnScreen('captures\\2-FirstName.png', grayscale=True, confidence=.8))

# Start filling personal details
pya.move(1000, 0)
time.sleep(1)
pya.typewrite("Ian")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Morrissey")
pya.press("tab")
pya.press("tab")
time.sleep(.25)
pya.typewrite("484-634-2960") # phone number has an incrementation button?
pya.press("tab")
time.sleep(.25)
pya.typewrite("ijm5157@psu.edu")
pya.press("tab")
time.sleep(.25)

# Start filling address
pya.typewrite("726 Eden Terrace")
pya.press("tab")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Easton")
pya.press("tab")
time.sleep(.25)
pya.typewrite("PA")
pya.press("tab")
time.sleep(.25)
pya.typewrite("18042")
pya.press("tab")
time.sleep(.25)
pya.typewrite("USA")

time.sleep(3)
pya.click(pya.locateCenterOnScreen('captures\\3-Next.png', grayscale=True, confidence=.8))

# Start Filling Objective
time.sleep(1)
pya.click(pya.locateCenterOnScreen('captures\\4-Position.png', grayscale=True, confidence=.8))
pya.move(1000, 0)
pya.typewrite("Summer Internship")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Obtain Summer 2019 IST Internship.")

time.sleep(3)
pya.click(pya.locateCenterOnScreen('captures\\3-Next.png', confidence=.8))

# Start Filling Social Profiles
time.sleep(1)
pya.click(pya.locateCenterOnScreen('captures\\5-LinkedIn.png', grayscale=True, confidence=.8))
pya.move(1000, 0)
pya.typewrite("https://www.linkedin.com/in/ian-morrissey/")
pya.press("tab")
time.sleep(.25)
pya.typewrite("https://github.com/IJM5157")
time.sleep(3)
pya.click(pya.locateCenterOnScreen('captures\\3-Next.png', confidence=.8))

# Start Filling Education
time.sleep(1)
pya.click(pya.locateCenterOnScreen('captures\\6-Institution.png', grayscale=True, confidence=.8))
pya.move(1000, 0)
pya.typewrite("Penn State - Berks")
pya.press("tab")
time.sleep(.25)
pya.typewrite("1801 Broadcasting Road")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Reading")
pya.press("tab")
time.sleep(.25)
pya.typewrite("PA")
pya.press("tab")
time.sleep(.25)
pya.typewrite("19610")
pya.press("tab")
time.sleep(.25)
pya.typewrite("USA")
pya.press("pgdn")
pya.press("tab")
time.sleep(.25)

for i in range(3):
    pya.press("down")

pya.press("tab")
time.sleep(.25)
pya.typewrite("Information Sciences and Technology")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Security amd Risk Analysis")
pya.press("tab")
time.sleep(.25)
pya.typewrite("3.95")
pya.press("tab")
time.sleep(.25)
pya.typewrite("May")
pya.press("tab")
pya.typewrite("2020")
time.sleep(3)
pya.click(pya.locateCenterOnScreen('captures\\3-Next.png', confidence=.8))

# Start Filling Relevant Courses
time.sleep(1)
pya.click(pya.locateCenterOnScreen('captures\\7-CourseName.png', grayscale=True, confidence=.8))
pya.move(1000, 0)
pya.typewrite("Networking and Telecommunications")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Course addressed network design and implementation issues at each network layer as well as common network applications.")
pya.press("tab")
time.sleep(.25)
pya.press("enter")
pya.click(pya.locateCenterOnScreen('captures\\8-Course2.png', confidence=.8))
pya.move(1000, 0)
time.sleep(.25)
pya.typewrite("Computer and Cyber Forensics")
pya.press("tab")
time.sleep(.25)
pya.typewrite("Course addressed the fundamental issues and concepts of computer forensics; aspects of computer and cyber crime; methods to uncover, protect, exploit, and document digital evidence; tools, techniques, and procedure to perform computer and cyber crime investigation.")
time.sleep(3)
pya.click(pya.locateCenterOnScreen('captures\\3-Next.png', confidence=.8))